/*
 * jPhonePanel.java
 *
 * Created on Mar 22, 2010, 6:31:03 PM
 *
 * @author pquiring@gmail.com
 *
 */

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.io.*;
import java.net.*;
import java.util.*;

import javaforce.*;
import javaforce.voip.*;
import javaforce.jni.*;
import javaforce.linux.Linux;

/** jphonelite Panel */

public class PhonePanel extends BasePhone implements MeterController, GUI, VideoController {

  /** Creates new form jPhonePanel */
  public PhonePanel(WindowController wc, boolean isApplet) {
    try {
      initBasePhone(this, wc);
      Settings.isApplet = isApplet;
      initComponents();
      init();
      if (isApplet) {
        sidePanel.setVisible(false);
      }
      //must set focus to something or VK_BACK_SPACE beeps
      SwingUtilities.invokeLater(new Runnable(){
        public void run(){
          call.requestFocusInWindow();  //must be called from EDT or when window is visible
        }
      });
    } catch (Exception e) {
      JFLog.log("Error:" + e);
    }
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    shareDesktopMenu = new javax.swing.JPopupMenu();
    shareDesktopViewOnly = new javax.swing.JMenuItem();
    shareDesktopRemoteControl = new javax.swing.JMenuItem();
    l1 = new javax.swing.JToggleButton();
    l2 = new javax.swing.JToggleButton();
    l3 = new javax.swing.JToggleButton();
    l4 = new javax.swing.JToggleButton();
    l5 = new javax.swing.JToggleButton();
    l6 = new javax.swing.JToggleButton();
    xfr = new javax.swing.JButton();
    hld = new javax.swing.JButton();
    aa = new javax.swing.JButton();
    ac = new javax.swing.JButton();
    dnd = new javax.swing.JButton();
    cnf = new javax.swing.JButton();
    call = new javax.swing.JToggleButton();
    end = new javax.swing.JToggleButton();
    n1 = new javax.swing.JButton();
    n2 = new javax.swing.JButton();
    n3 = new javax.swing.JButton();
    n4 = new javax.swing.JButton();
    n5 = new javax.swing.JButton();
    n6 = new javax.swing.JButton();
    n7 = new javax.swing.JButton();
    n8 = new javax.swing.JButton();
    n9 = new javax.swing.JButton();
    n0 = new javax.swing.JButton();
    nstar = new javax.swing.JButton();
    npound = new javax.swing.JButton();
    cfg = new javax.swing.JButton();
    clear = new javax.swing.JButton();
    redial = new javax.swing.JButton();
    status = new javax.swing.JTextField();
    dial = new javax.swing.JTextField();
    sidePanel = new javax.swing.JToggleButton();
    contactLabel = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    contactJList = new javax.swing.JList();
    recentLabel = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    recentList = new javax.swing.JList();
    delContact = new javax.swing.JButton();
    addContact = new javax.swing.JButton();
    editContact = new javax.swing.JButton();
    meterRec = new javax.swing.JProgressBar();
    meterPlay = new javax.swing.JProgressBar();
    mute = new javax.swing.JButton();
    headsetPic = new javax.swing.JLabel();
    micPic = new javax.swing.JLabel();
    backSpace = new javax.swing.JButton();
    micScale = new javax.swing.JLabel();
    spkScale = new javax.swing.JLabel();
    volRec = new javax.swing.JSlider();
    volPlay = new javax.swing.JSlider();
    presenceStatus = new javax.swing.JComboBox();
    jLabel1 = new javax.swing.JLabel();
    spk = new javax.swing.JButton();
    labels1 = new javax.swing.JLabel();
    spkPic = new javax.swing.JLabel();
    mutePic = new javax.swing.JLabel();
    labels2 = new javax.swing.JLabel();
    videoPanel = new javax.swing.JButton();
    fullScreenPic = new javax.swing.JLabel();
    enableVideoPic = new javax.swing.JLabel();
    videoPic = new javax.swing.JLabel();
    record = new javax.swing.JButton();
    recordPic = new javax.swing.JLabel();

    shareDesktopViewOnly.setText("Share Desktop (view only)");
    shareDesktopMenu.add(shareDesktopViewOnly);

    shareDesktopRemoteControl.setText("Share Desktop (remote control)");
    shareDesktopMenu.add(shareDesktopRemoteControl);

    setMaximumSize(new java.awt.Dimension(560, 350));
    setMinimumSize(new java.awt.Dimension(290, 350));
    setLayout(null);

    l1.setToolTipText("Line 1");
    l1.setMargin(new java.awt.Insets(2, 2, 2, 2));
    l1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        l1ActionPerformed(evt);
      }
    });
    add(l1);
    l1.setBounds(10, 70, 30, 30);

    l2.setToolTipText("Line 2");
    l2.setMargin(new java.awt.Insets(2, 2, 2, 2));
    l2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        l2ActionPerformed(evt);
      }
    });
    add(l2);
    l2.setBounds(50, 70, 30, 30);

    l3.setToolTipText("Line 3");
    l3.setMargin(new java.awt.Insets(2, 2, 2, 2));
    l3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        l3ActionPerformed(evt);
      }
    });
    add(l3);
    l3.setBounds(90, 70, 30, 30);

    l4.setToolTipText("Line 4");
    l4.setMargin(new java.awt.Insets(2, 2, 2, 2));
    l4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        l4ActionPerformed(evt);
      }
    });
    add(l4);
    l4.setBounds(130, 70, 30, 30);

    l5.setToolTipText("Line 5");
    l5.setMargin(new java.awt.Insets(2, 2, 2, 2));
    l5.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        l5ActionPerformed(evt);
      }
    });
    add(l5);
    l5.setBounds(170, 70, 30, 30);

    l6.setToolTipText("Line 6");
    l6.setMargin(new java.awt.Insets(2, 2, 2, 2));
    l6.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        l6ActionPerformed(evt);
      }
    });
    add(l6);
    l6.setBounds(210, 70, 30, 30);

    xfr.setToolTipText("Transfer");
    xfr.setMargin(new java.awt.Insets(2, 0, 2, 0));
    xfr.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        xfrActionPerformed(evt);
      }
    });
    add(xfr);
    xfr.setBounds(10, 110, 30, 30);

    hld.setToolTipText("Hold");
    hld.setMargin(new java.awt.Insets(2, 0, 2, 0));
    hld.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        hldActionPerformed(evt);
      }
    });
    add(hld);
    hld.setBounds(50, 110, 30, 30);

    aa.setToolTipText("Auto Answer");
    aa.setMargin(new java.awt.Insets(2, 0, 2, 0));
    aa.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        aaActionPerformed(evt);
      }
    });
    add(aa);
    aa.setBounds(130, 110, 30, 30);

    ac.setToolTipText("Auto Conference");
    ac.setMargin(new java.awt.Insets(2, 0, 2, 0));
    ac.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        acActionPerformed(evt);
      }
    });
    add(ac);
    ac.setBounds(170, 110, 30, 30);

    dnd.setToolTipText("Do-Not-Disturb");
    dnd.setMargin(new java.awt.Insets(2, 0, 2, 0));
    dnd.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        dndActionPerformed(evt);
      }
    });
    add(dnd);
    dnd.setBounds(210, 110, 30, 30);

    cnf.setToolTipText("Conference");
    cnf.setMargin(new java.awt.Insets(2, 0, 2, 0));
    cnf.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cnfActionPerformed(evt);
      }
    });
    add(cnf);
    cnf.setBounds(250, 110, 30, 30);

    call.setText("Call");
    call.setFocusCycleRoot(true);
    call.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        callActionPerformed(evt);
      }
    });
    add(call);
    call.setBounds(10, 150, 70, 50);

    end.setText("End");
    end.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        endActionPerformed(evt);
      }
    });
    add(end);
    end.setBounds(210, 150, 70, 50);

    n1.setText("1");
    n1.setMargin(new java.awt.Insets(2, 2, 2, 2));
    n1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        n1ActionPerformed(evt);
      }
    });
    add(n1);
    n1.setBounds(90, 150, 30, 30);

    n2.setText("2");
    n2.setMargin(new java.awt.Insets(2, 2, 2, 2));
    n2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        n2ActionPerformed(evt);
      }
    });
    add(n2);
    n2.setBounds(130, 150, 30, 30);

    n3.setText("3");
    n3.setMargin(new java.awt.Insets(2, 2, 2, 2));
    n3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        n3ActionPerformed(evt);
      }
    });
    add(n3);
    n3.setBounds(170, 150, 30, 30);

    n4.setText("4");
    n4.setMargin(new java.awt.Insets(2, 2, 2, 2));
    n4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        n4ActionPerformed(evt);
      }
    });
    add(n4);
    n4.setBounds(90, 190, 30, 30);

    n5.setText("5");
    n5.setMargin(new java.awt.Insets(2, 2, 2, 2));
    n5.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        n5ActionPerformed(evt);
      }
    });
    add(n5);
    n5.setBounds(130, 190, 30, 30);

    n6.setText("6");
    n6.setMargin(new java.awt.Insets(2, 2, 2, 2));
    n6.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        n6ActionPerformed(evt);
      }
    });
    add(n6);
    n6.setBounds(170, 190, 30, 30);

    n7.setText("7");
    n7.setMargin(new java.awt.Insets(2, 2, 2, 2));
    n7.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        n7ActionPerformed(evt);
      }
    });
    add(n7);
    n7.setBounds(90, 230, 30, 30);

    n8.setText("8");
    n8.setMargin(new java.awt.Insets(2, 2, 2, 2));
    n8.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        n8ActionPerformed(evt);
      }
    });
    add(n8);
    n8.setBounds(130, 230, 30, 30);

    n9.setText("9");
    n9.setMargin(new java.awt.Insets(2, 2, 2, 2));
    n9.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        n9ActionPerformed(evt);
      }
    });
    add(n9);
    n9.setBounds(170, 230, 30, 30);

    n0.setText("0");
    n0.setMargin(new java.awt.Insets(2, 2, 2, 2));
    n0.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        n0ActionPerformed(evt);
      }
    });
    add(n0);
    n0.setBounds(130, 270, 30, 30);

    nstar.setText("*");
    nstar.setMargin(new java.awt.Insets(2, 2, 2, 2));
    nstar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        nstarActionPerformed(evt);
      }
    });
    add(nstar);
    nstar.setBounds(90, 270, 30, 30);

    npound.setText("#");
    npound.setMargin(new java.awt.Insets(2, 2, 2, 2));
    npound.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        npoundActionPerformed(evt);
      }
    });
    add(npound);
    npound.setBounds(170, 270, 30, 30);

    cfg.setToolTipText("Configure");
    cfg.setMargin(new java.awt.Insets(2, 0, 2, 0));
    cfg.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cfgActionPerformed(evt);
      }
    });
    add(cfg);
    cfg.setBounds(250, 70, 30, 30);

    clear.setText("CLR");
    clear.setToolTipText("Clear");
    clear.setMargin(new java.awt.Insets(2, 0, 2, 0));
    clear.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        clearActionPerformed(evt);
      }
    });
    add(clear);
    clear.setBounds(170, 310, 30, 30);

    redial.setToolTipText("Redial");
    redial.setMargin(new java.awt.Insets(2, 0, 2, 0));
    redial.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        redialActionPerformed(evt);
      }
    });
    add(redial);
    redial.setBounds(90, 110, 30, 30);

    status.setEditable(false);
    add(status);
    status.setBounds(10, 40, 240, 20);

    dial.setEditable(false);
    add(dial);
    dial.setBounds(10, 10, 240, 20);

    sidePanel.setText(">");
    sidePanel.setMargin(new java.awt.Insets(2, 0, 2, 0));
    sidePanel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        sidePanelActionPerformed(evt);
      }
    });
    add(sidePanel);
    sidePanel.setBounds(260, 10, 20, 50);

    contactLabel.setText("Contacts");
    add(contactLabel);
    contactLabel.setBounds(290, 10, 70, 10);

    contactJList.setModel(new javax.swing.AbstractListModel() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public Object getElementAt(int i) { return strings[i]; }
    });
    contactJList.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        contactJListMouseClicked(evt);
      }
    });
    contactJList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
      public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
        contactJListValueChanged(evt);
      }
    });
    jScrollPane1.setViewportView(contactJList);

    add(jScrollPane1);
    jScrollPane1.setBounds(290, 30, 250, 150);

    recentLabel.setText("Recent Calls");
    add(recentLabel);
    recentLabel.setBounds(290, 190, 80, 10);

    recentList.setModel(new javax.swing.AbstractListModel() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public Object getElementAt(int i) { return strings[i]; }
    });
    recentList.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        recentListMouseClicked(evt);
      }
    });
    recentList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
      public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
        recentListValueChanged(evt);
      }
    });
    jScrollPane2.setViewportView(recentList);

    add(jScrollPane2);
    jScrollPane2.setBounds(290, 210, 250, 130);

    delContact.setText("Remove");
    delContact.setMargin(new java.awt.Insets(2, 0, 2, 0));
    delContact.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        delContactActionPerformed(evt);
      }
    });
    add(delContact);
    delContact.setBounds(480, 10, 60, 20);

    addContact.setText("Add");
    addContact.setMargin(new java.awt.Insets(2, 0, 2, 0));
    addContact.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        addContactActionPerformed(evt);
      }
    });
    add(addContact);
    addContact.setBounds(360, 10, 50, 20);

    editContact.setText("Edit");
    editContact.setMargin(new java.awt.Insets(2, 0, 2, 0));
    editContact.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        editContactActionPerformed(evt);
      }
    });
    add(editContact);
    editContact.setBounds(420, 10, 50, 20);

    meterRec.setOrientation(1);
    add(meterRec);
    meterRec.setBounds(30, 210, 10, 90);

    meterPlay.setOrientation(1);
    add(meterPlay);
    meterPlay.setBounds(270, 210, 10, 90);

    mute.setToolTipText("Mute");
    mute.setMargin(new java.awt.Insets(2, 0, 2, 0));
    mute.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        muteActionPerformed(evt);
      }
    });
    add(mute);
    mute.setBounds(10, 310, 30, 30);

    headsetPic.setText(".");
    add(headsetPic);
    headsetPic.setBounds(210, 230, 30, 30);

    micPic.setText(".");
    add(micPic);
    micPic.setBounds(50, 230, 30, 30);

    backSpace.setText("<");
    backSpace.setMargin(new java.awt.Insets(2, 2, 2, 2));
    backSpace.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        backSpaceActionPerformed(evt);
      }
    });
    add(backSpace);
    backSpace.setBounds(90, 310, 30, 30);

    micScale.setText(".");
    add(micScale);
    micScale.setBounds(20, 210, 10, 90);

    spkScale.setText(".");
    add(spkScale);
    spkScale.setBounds(260, 210, 10, 90);

    volRec.setOrientation(javax.swing.JSlider.VERTICAL);
    volRec.setValue(75);
    volRec.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        volRecStateChanged(evt);
      }
    });
    add(volRec);
    volRec.setBounds(0, 210, 20, 90);

    volPlay.setOrientation(javax.swing.JSlider.VERTICAL);
    volPlay.setValue(75);
    volPlay.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        volPlayStateChanged(evt);
      }
    });
    add(volPlay);
    volPlay.setBounds(240, 210, 20, 90);

    presenceStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Auto", "DND", "Busy", "Idle", "Offline" }));
    presenceStatus.setEnabled(false);
    presenceStatus.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        presenceStatusItemStateChanged(evt);
      }
    });
    add(presenceStatus);
    presenceStatus.setBounds(450, 185, 90, 20);

    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    jLabel1.setText("Status:");
    add(jLabel1);
    jLabel1.setBounds(380, 190, 70, 10);

    spk.setToolTipText("Speaker Phone Mode");
    spk.setMargin(new java.awt.Insets(2, 0, 2, 0));
    spk.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        spkActionPerformed(evt);
      }
    });
    add(spk);
    spk.setBounds(250, 310, 30, 30);
    add(labels1);
    labels1.setBounds(10, 100, 270, 10);
    add(spkPic);
    spkPic.setBounds(250, 340, 30, 10);
    add(mutePic);
    mutePic.setBounds(10, 340, 30, 10);
    add(labels2);
    labels2.setBounds(10, 140, 270, 10);

    videoPanel.setToolTipText("Show Video Panel");
    videoPanel.setMargin(new java.awt.Insets(2, 0, 2, 0));
    videoPanel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        videoPanelActionPerformed(evt);
      }
    });
    add(videoPanel);
    videoPanel.setBounds(210, 310, 30, 30);
    add(fullScreenPic);
    fullScreenPic.setBounds(470, 670, 60, 10);
    add(enableVideoPic);
    enableVideoPic.setBounds(20, 670, 60, 10);
    add(videoPic);
    videoPic.setBounds(210, 340, 30, 10);

    record.setToolTipText("Record");
    record.setMargin(new java.awt.Insets(2, 0, 2, 0));
    record.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        recordActionPerformed(evt);
      }
    });
    add(record);
    record.setBounds(50, 310, 30, 30);
    add(recordPic);
    recordPic.setBounds(50, 340, 30, 10);
  }// </editor-fold>//GEN-END:initComponents

    private void n3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n3ActionPerformed
      addDigit('3');
    }//GEN-LAST:event_n3ActionPerformed

    private void cfgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cfgActionPerformed
      for(int a=0;a<6;a++) { if (lines[a].incall) return; }
      if (showingVideo) {
        toggleVideoPanel();
      }
      cfg.setIcon(ii[PIC_GREEN]);
      unRegisterAll();
      selectLine(-1);
      sound.uninit();
      dial.setText("");
      status.setText("");
      EditSettings.editSettings(null);
      setFonts();
      JFLog.setEnabled(!Settings.current.disableLogging);
      wc.setPanelAlwaysOnTop(Settings.current.alwaysOnTop);
      loadingConfig = true;
      updateContactList();
      loadingConfig = false;
      updateRecentList();
      if (!sound.init(lines, this)) {
        JOptionPane.showMessageDialog(this,
          "No compatible sound found",
          "Warning",
          JOptionPane.INFORMATION_MESSAGE);
      }
      setPresenceStatus();
      setScales();
      reRegisterAll();
      cfg.setIcon(ii[PIC_GREY]);

      if (((Settings.current.videoType == Settings.VIDEO_LINUX) && (Settings.isLinux))
      || ((Settings.current.videoType == Settings.VIDEO_WINDOWS) && (Settings.isWindows))) {
        videoPanel.setEnabled(true);
      } else {
        videoPanel.setEnabled(false);
      }
    }//GEN-LAST:event_cfgActionPerformed

    private void n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n1ActionPerformed
      addDigit('1');
    }//GEN-LAST:event_n1ActionPerformed

    private void n2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n2ActionPerformed
      addDigit('2');
    }//GEN-LAST:event_n2ActionPerformed

    private void n4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n4ActionPerformed
      addDigit('4');
    }//GEN-LAST:event_n4ActionPerformed

    private void n5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n5ActionPerformed
      addDigit('5');
    }//GEN-LAST:event_n5ActionPerformed

    private void n6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n6ActionPerformed
      addDigit('6');
    }//GEN-LAST:event_n6ActionPerformed

    private void n7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n7ActionPerformed
      addDigit('7');
    }//GEN-LAST:event_n7ActionPerformed

    private void n8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n8ActionPerformed
      addDigit('8');
    }//GEN-LAST:event_n8ActionPerformed

    private void n9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n9ActionPerformed
      addDigit('9');
    }//GEN-LAST:event_n9ActionPerformed

    private void nstarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nstarActionPerformed
      addDigit('*');
    }//GEN-LAST:event_nstarActionPerformed

    private void n0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n0ActionPerformed
      addDigit('0');
    }//GEN-LAST:event_n0ActionPerformed

    private void npoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npoundActionPerformed
      addDigit('#');
    }//GEN-LAST:event_npoundActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
      clear();
    }//GEN-LAST:event_clearActionPerformed

    private void callActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_callActionPerformed
      call();
    }//GEN-LAST:event_callActionPerformed

    private void endActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endActionPerformed
      end();
    }//GEN-LAST:event_endActionPerformed

    private void l1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l1ActionPerformed
      selectLine(0);
    }//GEN-LAST:event_l1ActionPerformed

    private void l2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l2ActionPerformed
      selectLine(1);
    }//GEN-LAST:event_l2ActionPerformed

    private void l3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l3ActionPerformed
      selectLine(2);
    }//GEN-LAST:event_l3ActionPerformed

    private void l4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l4ActionPerformed
      selectLine(3);
    }//GEN-LAST:event_l4ActionPerformed

    private void l5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l5ActionPerformed
      selectLine(4);
    }//GEN-LAST:event_l5ActionPerformed

    private void l6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l6ActionPerformed
      selectLine(5);
    }//GEN-LAST:event_l6ActionPerformed

    private void xfrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xfrActionPerformed
      doXfer();
    }//GEN-LAST:event_xfrActionPerformed

    private void hldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hldActionPerformed
      doHold();
    }//GEN-LAST:event_hldActionPerformed

    private void redialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redialActionPerformed
      doRedial();
    }//GEN-LAST:event_redialActionPerformed

    private void aaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aaActionPerformed
      toggleAA();
    }//GEN-LAST:event_aaActionPerformed

    private void acActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acActionPerformed
      toggleAC();
    }//GEN-LAST:event_acActionPerformed

    private void dndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dndActionPerformed
      toggleDND();
    }//GEN-LAST:event_dndActionPerformed

    private void cnfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnfActionPerformed
      doConference();
    }//GEN-LAST:event_cnfActionPerformed

    private void sidePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidePanelActionPerformed
      toggleContacts();
    }//GEN-LAST:event_sidePanelActionPerformed

    private void addContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addContactActionPerformed
      addContact();
    }//GEN-LAST:event_addContactActionPerformed

    private void delContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delContactActionPerformed
      delContact();
    }//GEN-LAST:event_delContactActionPerformed

    private void contactJListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_contactJListValueChanged
//      dialContact();
    }//GEN-LAST:event_contactJListValueChanged

    private void recentListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_recentListValueChanged
//      dialRecent();
    }//GEN-LAST:event_recentListValueChanged

    private void contactJListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactJListMouseClicked
      if (evt.getClickCount() == 2) dialContact();
    }//GEN-LAST:event_contactJListMouseClicked

    private void recentListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recentListMouseClicked
      if (evt.getClickCount() == 2) dialRecent();
    }//GEN-LAST:event_recentListMouseClicked

    private void editContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editContactActionPerformed
      editContact();
    }//GEN-LAST:event_editContactActionPerformed

    private void muteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muteActionPerformed
      toggleMute();
    }//GEN-LAST:event_muteActionPerformed

    private void backSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backSpaceActionPerformed
      addDigit((char)KeyEvent.VK_BACK_SPACE);
    }//GEN-LAST:event_backSpaceActionPerformed

    private void volRecStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_volRecStateChanged
      setVolRec();
    }//GEN-LAST:event_volRecStateChanged

    private void volPlayStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_volPlayStateChanged
      setVolPlay();
    }//GEN-LAST:event_volPlayStateChanged

    private void presenceStatusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_presenceStatusItemStateChanged
      publishPresence();
    }//GEN-LAST:event_presenceStatusItemStateChanged

    private void spkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spkActionPerformed
      toggleSpeaker();
    }//GEN-LAST:event_spkActionPerformed

  private void videoPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_videoPanelActionPerformed
    toggleVideoPanel();
  }//GEN-LAST:event_videoPanelActionPerformed

  private void recordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordActionPerformed
    toggleRecord();
  }//GEN-LAST:event_recordActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton aa;
  private javax.swing.JButton ac;
  private javax.swing.JButton addContact;
  private javax.swing.JButton backSpace;
  private javax.swing.JToggleButton call;
  private javax.swing.JButton cfg;
  private javax.swing.JButton clear;
  private javax.swing.JButton cnf;
  private javax.swing.JList contactJList;
  private javax.swing.JLabel contactLabel;
  private javax.swing.JButton delContact;
  private javax.swing.JTextField dial;
  private javax.swing.JButton dnd;
  private javax.swing.JButton editContact;
  private javax.swing.JLabel enableVideoPic;
  private javax.swing.JToggleButton end;
  private javax.swing.JLabel fullScreenPic;
  private javax.swing.JLabel headsetPic;
  private javax.swing.JButton hld;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JToggleButton l1;
  private javax.swing.JToggleButton l2;
  private javax.swing.JToggleButton l3;
  private javax.swing.JToggleButton l4;
  private javax.swing.JToggleButton l5;
  private javax.swing.JToggleButton l6;
  private javax.swing.JLabel labels1;
  private javax.swing.JLabel labels2;
  private javax.swing.JProgressBar meterPlay;
  private javax.swing.JProgressBar meterRec;
  private javax.swing.JLabel micPic;
  private javax.swing.JLabel micScale;
  private javax.swing.JButton mute;
  private javax.swing.JLabel mutePic;
  private javax.swing.JButton n0;
  private javax.swing.JButton n1;
  private javax.swing.JButton n2;
  private javax.swing.JButton n3;
  private javax.swing.JButton n4;
  private javax.swing.JButton n5;
  private javax.swing.JButton n6;
  private javax.swing.JButton n7;
  private javax.swing.JButton n8;
  private javax.swing.JButton n9;
  private javax.swing.JButton npound;
  private javax.swing.JButton nstar;
  private javax.swing.JComboBox presenceStatus;
  private javax.swing.JLabel recentLabel;
  private javax.swing.JList recentList;
  private javax.swing.JButton record;
  private javax.swing.JLabel recordPic;
  private javax.swing.JButton redial;
  private javax.swing.JPopupMenu shareDesktopMenu;
  private javax.swing.JMenuItem shareDesktopRemoteControl;
  private javax.swing.JMenuItem shareDesktopViewOnly;
  private javax.swing.JToggleButton sidePanel;
  private javax.swing.JButton spk;
  private javax.swing.JLabel spkPic;
  private javax.swing.JLabel spkScale;
  private javax.swing.JTextField status;
  private javax.swing.JButton videoPanel;
  private javax.swing.JLabel videoPic;
  private javax.swing.JSlider volPlay;
  private javax.swing.JSlider volRec;
  private javax.swing.JButton xfr;
  // End of variables declaration//GEN-END:variables

  /** Init panel variables. */

  public void init() {
    loadIcons();
    Settings.loadSettings();
    if (new File("/usr/share/java/javaforce.jar").exists()) {
      if (LnxAPI.init() && LnxAPI.gst_init()) {
        Settings.isLinux = true;
        Settings.current.checkVersion = false;
        if (!Linux.isMemberOf(JF.getCurrentUser(), "video")) {
          JFLog.log("Warning:You must be a member of 'video' group to use video4linux");
          videoPanel.setEnabled(false);
        }
      }
    }
    if ((!Settings.isLinux) && (!Settings.isWindows)) {
      videoPanel.setEnabled(false);
    }
    if (((Settings.current.videoType == Settings.VIDEO_LINUX) && (Settings.isLinux))
      || ((Settings.current.videoType == Settings.VIDEO_WINDOWS) && (Settings.isWindows)))
    {
      videoPanel.setEnabled(true);
    } else {
      videoPanel.setEnabled(false);
    }
    setFonts();
    wc.setPanelAlwaysOnTop(Settings.current.alwaysOnTop);
    JFLog.setEnabled(!Settings.current.disableLogging);
    JFLog.log("jphonelite/" + version);

    contactJList.setCellRenderer(new ListCellRenderer() {
      public Component getListCellRendererComponent(
        JList list,              // the list
        Object value,            // value to display
        int index,               // cell index
        boolean isSelected,      // is the cell selected
        boolean cellHasFocus)    // does the cell have focus
      {
        //each Object 'is' a JLabel (Contact) which makes this easy
        JLabel label = (JLabel)value;
        if (isSelected) {
          label.setBackground(list.getSelectionBackground());
          label.setForeground(list.getSelectionForeground());
        } else {
          label.setBackground(list.getBackground());
          label.setForeground(list.getForeground());
        }
        label.setEnabled(list.isEnabled());
        label.setFont(list.getFont());
        label.setOpaque(true);
        return label;
     }
    });

    loadingConfig = true;
    updateContactList();
    loadingConfig = false;
    updateRecentList();
    if (!Settings.isApplet) {
      if (SystemTray.isSupported()) {
        tray = SystemTray.getSystemTray();
        // create a popup menu
        PopupMenu popup = new PopupMenu();
        show = new MenuItem("Show");
        show.addActionListener(this);
        popup.add(show);
        popup.addSeparator();
        exit = new MenuItem("Exit");
        exit.addActionListener(this);
        popup.add(exit);
        if (JF.isWindows()) {
          icon = new TrayIcon(ii[PIC_TRAY_16].getImage(), "jPhoneLite", popup);
        } else {
          icon = new TrayIcon(ii[PIC_TRAY_24].getImage(), "jPhoneLite", popup);
        }
        icon.addActionListener(this);
        try { tray.add(icon); } catch (Exception e) { JFLog.log(e); }
      }
    }
    lines = new PhoneLine[6];
    lineButtons = new JToggleButton[6];
    lineButtons[0] = l1;
    lineButtons[1] = l2;
    lineButtons[2] = l3;
    lineButtons[3] = l4;
    lineButtons[4] = l5;
    lineButtons[5] = l6;
    for(int a=0;a<6;a++) {
      lineButtons[a].setMargin(new Insets(0,0,0,0));
      lineButtons[a].setIconTextGap(0);
      lines[a] = new PhoneLine();
    }
    numButtons = new JButton[12];
    numButtons[0] = n1;
    numButtons[1] = n2;
    numButtons[2] = n3;
    numButtons[3] = n4;
    numButtons[4] = n5;
    numButtons[5] = n6;
    numButtons[6] = n7;
    numButtons[7] = n8;
    numButtons[8] = n9;
    numButtons[9] = n0;
    numButtons[10] = nstar;
    numButtons[11] = npound;
    for(int a=0;a<12;a++) {
      numButtons[a].addMouseListener(new MouseAdapter() {
        public void mousePressed(MouseEvent e) {
          JButton o = (JButton)e.getSource();
          pressDigit(o.getText().charAt(0));
        }
        public void mouseReleased(MouseEvent e) {
          JButton o = (JButton)e.getSource();
          releaseDigit(o.getText().charAt(0));
        }
      });
    }

    //set PICs

    call.setText("");
    call.setIcon(ii[PIC_CALL]);
//    call.setPressedIcon(ii[PIC_CALL2]);
    call.setSelectedIcon(ii[PIC_CALL2]);

    end.setText("");
    end.setIcon(ii[PIC_END]);
//    end.setPressedIcon(ii[PIC_END2]);
    end.setSelectedIcon(ii[PIC_END2]);

    labels1.setText("");
    labels1.setIcon(ii[PIC_LABELS1]);

    labels2.setText("");
    labels2.setIcon(ii[PIC_LABELS2]);

    micPic.setText("");
    micPic.setIcon(ii[PIC_MIC]);
    headsetPic.setText("");
    headsetPic.setIcon(ii[PIC_HEADSET]);

    spk.setText("");
    spk.setIcon(ii[Settings.current.speakerMode ? PIC_GREEN : PIC_GREY]);
    spkPic.setText("");
    spkPic.setIcon(ii[PIC_SPK]);

    videoPanel.setIcon(ii[PIC_GREY]);
    videoPic.setText("");
    videoPic.setIcon(ii[PIC_VIDEO]);

    mute.setText("");
    mute.setIcon(ii[PIC_GREY]);
    mutePic.setText("");
    mutePic.setIcon(ii[PIC_MUTE]);

    xfr.setText("");
    xfr.setIcon(ii[PIC_GREY]);
    hld.setText("");
    hld.setIcon(ii[PIC_GREY]);
    redial.setText("");
    redial.setIcon(ii[PIC_GREY]);
    aa.setText("");
    aa.setIcon(ii[PIC_GREY]);
    ac.setText("");
    ac.setIcon(ii[PIC_GREY]);
    dnd.setText("");
    dnd.setIcon(ii[PIC_GREY]);
    cnf.setText("");
    cnf.setIcon(ii[PIC_GREY]);
    cfg.setText("");
    cfg.setIcon(ii[PIC_GREY]);

    record.setIcon(ii[PIC_GREY]);
    recordPic.setText("");
    recordPic.setIcon(ii[PIC_RECORD]);

    setPresenceStatus();

    java.util.Timer buttontimer = new java.util.Timer();
    buttontimer.schedule(new ButtonColorUpdater(), 0, 250);

    keepAliveinit();
    boolean sound_init = sound.init(lines, this);
    setScales();  //requires sound.init()
    new Thread() {
      public void run() {
        reRegisterAll();
      }
    }.start();
    if (Settings.current.checkVersion) {
      new Thread() {
        public void run() {
          checkVersion();
       }
      }.start();
    }
    if (!sound_init) {
      JOptionPane.showMessageDialog(this,
        "No compatible sound found",
        "Warning",
        JOptionPane.INFORMATION_MESSAGE);
    }
  }

  /** MeterController : Sets the recording level on the display meter. */

  public void setMeterRec(int lvl) {meterRec.setValue(lvl);}

  /** MeterController : Sets the playback level on the display meter. */

  public void setMeterPlay(int lvl) {meterPlay.setValue(lvl);}

  /** MeterController : Sets the speaker mic status (green=true red=false). */

  public void setSpeakerStatus(boolean state) {
    if (!Settings.current.speakerMode) return;  //could happen just after turned off
    spk.setIcon(ii[state ? PIC_GREEN : PIC_RED]);
  }

  /** Change volume from slider control. */

  public void setVolRec() {
    sound.setVolRec(volRec.getValue());
  }

  /** Change volume from slider control. */

  public void setVolPlay() {
    sound.setVolPlay(volPlay.getValue());
  }

  public void setScales() {
    if (sound.isSWVolRec()) {
      micScale.setText("");
      micScale.setIcon(ii[PIC_SWSCALE]);
      volRec.setValue(75);
      sound.setVolRec(75);
    } else {
      micScale.setText("");
      micScale.setIcon(ii[PIC_HWSCALE]);
      volRec.setValue(100);
      sound.setVolRec(100);
    }
    if (sound.isSWVolPlay()) {
      spkScale.setText("");
      spkScale.setIcon(ii[PIC_SWSCALE]);
      volPlay.setValue(75);
      sound.setVolPlay(75);
    } else {
      spkScale.setText("");
      spkScale.setIcon(ii[PIC_HWSCALE]);
      volPlay.setValue(100);
      sound.setVolPlay(100);
    }
  }

  /** Select a new line. */

  public void selectLine(int newline) {
    //make sure line is valid
    for (int a=0;a<6;a++) lineButtons[a].setSelected(false);
    if ((line != -1) && (lines[line].dtmf != 'x')) lines[line].dtmfend = true;
    line = newline;
    if (line == -1) {
      dial.setText("");
      status.setText("");
      hld.setIcon(ii[PIC_GREY]);
      dnd.setIcon(ii[PIC_GREY]);
      cnf.setIcon(ii[PIC_GREY]);
      return;
    }
    lineButtons[line].setSelected(true);
    sound.selectLine(line);
    updateLine();
  }

  /** Update the number to be dialed, status and buttons for current selected line. */

  public void updateLine() {
    end.setSelected(false);
    if (lines[line].incall) {
      call.setSelected(true);
    } else {
      call.setSelected(false);
    }
    dial.setText(lines[line].dial);
    status.setText(lines[line].status);
    hld.setIcon(ii[lines[line].hld ? PIC_RED : PIC_GREY]);
    dnd.setIcon(ii[lines[line].dnd ? PIC_RED : PIC_GREY]);
    cnf.setIcon(ii[lines[line].cnf ? PIC_GREEN : PIC_GREY]);
    xfr.setIcon(ii[lines[line].xfer ? PIC_GREEN : PIC_GREY]);
  }

  public void updateCallButton(boolean state) {
    call.setSelected(state);
  }

  public void updateEndButton(boolean state) {
    end.setSelected(state);
  }

  public void endLineUpdate(int xline) {
    if ((Settings.current.usePublish) && (presenceStatus.getSelectedIndex() == 0)) lines[xline].sip.publish("open");
    if (showingVideo) {
      toggleVideoPanel();
    }
    if (sound.record != null) {
      toggleRecord();
    }
  }

  public void callInviteUpdate() {
    updateRecentList();
    if ((Settings.current.usePublish) && (presenceStatus.getSelectedIndex() == 0)) lines[line].sip.publish("busy");
  }

/*
Line Colors:
  black=not registered
  grey=available
  green=in use
  red=unauth
  green/grey=ringing
*/

  /** TimerTask executed every 250ms to change the line lights(icons). */

  public class ButtonColorUpdater extends java.util.TimerTask {
    public boolean odd = false;
    public void run() {
      int clr = PIC_BLACK;
      for(int a=0;a<6;a++) {
        if ((lines[a].sip != null) && (lines[a].auth)) {
          clr = PIC_GREY;
          if (lines[a].msgwaiting) {
            if (odd) clr = PIC_ORANGE;
          }
          if (lines[a].incoming) {
            if (odd) clr = PIC_GREEN; else clr = PIC_GREY;
          } else if (lines[a].incall) clr = PIC_GREEN;
        } else {
          if (lines[a].unauth)
            clr = PIC_RED;
          else
            clr = PIC_BLACK;
        }
        if (lines[a].clr != clr) {
          lineButtons[a].setIcon(ii[clr]);
          lines[a].clr = clr;
        }
      }
      odd = !odd;
    }
  }

  /** Sets a contacts icon status when received from a NOTIFY message. */

  public void setStatus(String number, String server, String status) {
    if (server.indexOf(':') == -1) server += ":5060";
    JFLog.log("setStatus(" + number + "," + server + "," + status);
    for(int a=0;a<contactList.size();a++) {
      String contact = contactList.get(a).contact;
      String fields[] = SIP.split(contact);
      if (fields[2].indexOf(':') == -1) fields[2] += ":5060";
      if ( (fields[1].equals(number)) && (fields[2].equals(server)) ) {
        if (status.equals("open")) {
          contactList.get(a).setIcon(ii[PIC_ICON_OPEN]);
          break;
        }
        if (status.equals("closed")) {
          contactList.get(a).setIcon(ii[PIC_ICON_CLOSED]);
          break;
        }
        if (status.equals("idle")) {
          contactList.get(a).setIcon(ii[PIC_ICON_IDLE]);
          break;
        }
        if (status.equals("busy")) {
          contactList.get(a).setIcon(ii[PIC_ICON_BUSY]);
          break;
        }
        if (status.equals("dnd")) {
          contactList.get(a).setIcon(ii[PIC_ICON_DND]);
          break;
        }
        break;
      }
    }
    contactJList.repaint();
  }

  /** Updates contact list after a change. */

  public void updateContactList() {
    int i1, i2;
    String fields1[], fields2[];
    //x = "display name" <sip:user@host;tag=...>;tag=...
    //return:    [0]          [1]  [2]   [...][:][...]
    for(int a=0;a<Settings.current.sipcontacts.length;a++) {
      fields1 = SIP.split(Settings.current.sipcontacts[a]);
      boolean ok = false;
      for(int b=0;b<contactList.size();b++) {
        fields2 = SIP.split(contactList.get(b).contact);
        if (fields1[0].equals(fields2[0])) {ok = true; break;}
      }
      if (!ok) {
        Contact contact = new Contact(fields1[0], Settings.current.sipcontacts[a]);
        contact.setIcon(ii[PIC_ICON_CLOSED]);
        contactList.add(contact);
        if (SIP.getFlag2(fields1, "monitor").equals("true")) addMonitor(Settings.current.sipcontacts[a]);
      }
    }
    contactJList.setListData(contactList.toArray());
  }

  /** Update recent lists after a change. */

  public void updateRecentList() {
    recentList.setListData(Settings.current.callLog);
  }

  /** Call a contact (double-click). */

  public void dialContact() {
    String contact = ((Contact)contactJList.getSelectedValue()).contact;
    String fields[] = SIP.split(contact);
    if (line == -1) return;
    if (lines[line].incall) return;
    if (fields[1].length() == 0) return;
    lines[line].dial = fields[1];
    call();
  }

  /** Call a recent number (double-click). */

  public void dialRecent() {
    if (line == -1) return;
    if (lines[line].incall) return;
    String dial = (String)recentList.getSelectedValue();
    if ((dial == null) || (dial.length() == 0)) return;
    lines[line].dial = dial;
    call();
  }

  /** Toggle side panel (contacts/recent lists). */

  public void toggleContacts() {
    showingContacts = !showingContacts;
    wc.setPanelSize();
    if (!showingContacts) {
      sidePanel.setText(">");
    } else {
      sidePanel.setText("<");
    }
  }

  public void toggleVideoPanel() {
    if (!showingVideo) {
      if (line == -1) {
        return;
      }
      if (!lines[line].talking) {
        return;
      }
      if (!SIP.hasCodec(lines[line].codecs, RTP.CODEC_JPEG)) {
        return;
      }
    }
    showingVideo = !showingVideo;
    videoPanel.setIcon(ii[showingVideo ? PIC_GREEN : PIC_GREY]);
    toggleVideoActive();
  }

  private void toggleVideoActive() {
    if (Settings.isLinux) {
      if (showingVideo) {
        videoWindow = new VideoWindow(this);
        localCamera = new LocalCamera();
        localCamera.start();
        remoteCamera = new RemoteCamera();
        remoteCamera.start();
      } else {
        localCamera.cancel();
        localCamera = null;
        remoteCamera.cancel();
        remoteCamera = null;
        videoWindow.dispose();
      }
    } else if (Settings.isWindows) {
      if (showingVideo) {
        videoWindow = new VideoWindow(this);
        wlocalCamera = new WLocalCamera();
        wlocalCamera.start();
        wremoteCamera = new WRemoteCamera();
        wremoteCamera.start();
      } else {
        wlocalCamera.cancel();
        wlocalCamera = null;
        wremoteCamera.cancel();
        wremoteCamera = null;
        videoWindow.dispose();
      }
    }
  }

  /** Adds a new contact. */

  public void addContact() {
    String contact = EditContact.editContact(null, "\"New User\"<sip:@>", true);
    if (contact == null) return;
    String fields[] = SIP.split(contact);
    Settings.setContact(fields[0], contact);
    updateContactList();
    Settings.saveSettings();
  }

  /** Edits an existing contact. */

  public void editContact() {
    Contact label = (Contact)contactJList.getSelectedValue();
    if (label == null) return;
    String contact = label.contact;
    String orgcontact = contact;
    String orgfields[] = SIP.split(contact);
    String orgname = orgfields[0];
    contact = EditContact.editContact(null, contact, false);
    if (contact == null) return;
    String fields[] = SIP.split(contact);
    if (!fields[0].equals(orgname)) {
      Settings.delContact(orgname);
      if (SIP.getFlag2(orgfields, "monitor").equals("true")) delMonitor(orgcontact);
      for(int a=0;a<contactList.size();a++) {
        String fields2[] = SIP.split(contactList.get(a).contact);
        if (fields2[0].equals(orgname)) {
          contactList.remove(a);
          break;
        }
      }
    } else {
      if ((SIP.getFlag2(orgfields, "monitor").equals("true")) && (SIP.getFlag2(fields, "monitor").equals("false"))) delMonitor(orgcontact);
      for(int a=0;a<contactList.size();a++) {
        String fields2[] = SIP.split(contactList.get(a).contact);
        if (fields2[0].equals(fields[0])) {
          contactList.get(a).contact = contact;
          break;
        }
      }
    }
    Settings.setContact(fields[0], contact);
    updateContactList();
    Settings.saveSettings();
  }

  /** Deletes a contact. */

  public void delContact() {
    Contact label = (Contact)contactJList.getSelectedValue();
    if (label == null) return;
    String contact = label.contact;
    String fields[] = SIP.split(contact);
    if (JOptionPane.showConfirmDialog(this, "Delete " + fields[0] + "?", "Delete entry?", JOptionPane.YES_NO_OPTION) != JOptionPane.YES_OPTION) return;
    Settings.delContact(fields[0]);
    for(int a=0;a<contactList.size();a++) {
      String fields2[] = SIP.split(contactList.get(a).contact);
      if (fields2[0].equals(fields[0])) {
        contactList.remove(a);
        break;
      }
    }
    updateContactList();
    Settings.saveSettings();
    if (SIP.getFlag2(fields, "monitor").equals("true")) delMonitor(contact);
  }

  public void hld_setIcon(ImageIcon ii) {
    hld.setIcon(ii);
  }

  public void aa_setIcon(ImageIcon ii) {
    aa.setIcon(ii);
  }

  public void ac_setIcon(ImageIcon ii) {
    ac.setIcon(ii);
  }

  public void dnd_setIcon(ImageIcon ii) {
    dnd.setIcon(ii);
  }

  public void cnf_setIcon(ImageIcon ii) {
    cnf.setIcon(ii);
  }

  public void mute_setIcon(ImageIcon ii) {
    mute.setIcon(ii);
  }

  public void spk_setIcon(ImageIcon ii) {
    spk.setIcon(ii);
  }

  public void setFonts() {
//    JFLog.log("Font name= " + l1.getFont().getName() + ",stype=" + l1.getFont().getStyle() + ",size=" + l1.getFont().getSize() );
    //sets font sizes for all buttons
    int small = 10;
    int large = 12;  //default size
    if (Settings.current.smallerFont) {
      small -= 2;
      large -= 2;
    }
    Font smallFont = new java.awt.Font("Dialog", 0, small);
    Font largeFont = new java.awt.Font("Dialog", 0, large);

    //these components use three or more letter and require a smaller font
    cfg.setFont(smallFont);
    xfr.setFont(smallFont);
    hld.setFont(smallFont);
    dnd.setFont(smallFont);
    cnf.setFont(smallFont);
    mute.setFont(smallFont);
    clear.setFont(smallFont);
    //the remaining components are okay with the normal font
    l1.setFont(largeFont);
    l2.setFont(largeFont);
    l3.setFont(largeFont);
    l4.setFont(largeFont);
    l5.setFont(largeFont);
    l6.setFont(largeFont);
    redial.setFont(largeFont);
    aa.setFont(largeFont);
    ac.setFont(largeFont);
    sidePanel.setFont(largeFont);
    addContact.setFont(largeFont);
    editContact.setFont(largeFont);
    delContact.setFont(largeFont);
    contactLabel.setFont(largeFont);
    recentLabel.setFont(largeFont);
  }

  public void setPresenceStatus() {
    presenceStatus.setSelectedIndex(0);
    if (Settings.current.usePublish) {
      presenceStatus.setEnabled(true);
    } else {
      presenceStatus.setEnabled(false);
    }
  }

  public void publishPresence() {
    if (line == -1) return;
    String state = (String)presenceStatus.getSelectedItem();
    if (state.equals("Auto")) {
      if (lines[line].incall) state = "busy"; else state = "open";
    } else if (state.equals("DND")) {
      state = "dnd";
    } else if (state.equals("Busy")) {
      state = "busy";
    } else if (state.equals("Idle")) {
      state = "idle";
    } else if (state.equals("Offline")) {
      state = "closed";
    }
    for(int a=0;a<6;a++) {
      if (Settings.current.lines[a].same != -1) continue;
      if (lines[a].sip == null) continue;
      if (!lines[a].sip.isRegistered()) continue;
      lines[a].sip.publish(state);
    }
  }

  public void addMonitor(String contact) {
    String fields[] = SIP.split(contact);
    //only want first 3 fields in the monitorList
    String fields3[] = new String[3];
    fields3[0] = fields[0];
    fields3[1] = fields[1];
    fields3[2] = fields[2];
    String contact3 = SIP.join(fields3);
    monitorList.add(contact3);
    if (loadingConfig) return;
    //we need to see if a SIP is already registered that we can subscribe to
    for(int a=0;a<6;a++) {
      if (lines[a].sip == null) continue;
      if (!lines[a].sip.isRegistered()) continue;
      if (lines[a].sip.getRemoteHost().equals(fields[3])) {
        //found one that matches
        lines[a].sip.subscribe(fields3[1], "presence", 3600);
        return;
      }
    }
  }

  public void delMonitor(String contact) {
    String fields[] = SIP.split(contact);
    String fields3[] = new String[3];
    fields3[0] = fields[0];
    fields3[1] = fields[1];
    fields3[2] = fields[2];
    String contact3 = SIP.join(fields3);
    for(int a=0;a<monitorList.size();a++) {
      if (monitorList.get(a).equals(contact3)) {
        monitorList.remove(a);
        break;
      }
    }
    if (loadingConfig) return;
    //we need to see if a SIP is already registered that we can subscribe to
    for(int a=0;a<6;a++) {
      if (lines[a].sip == null) continue;
      if (!lines[a].sip.isRegistered()) continue;
      if (lines[a].sip.getRemoteHost().equals(fields[3])) {
        //found one that matches
        lines[a].sip.subscribe(fields3[1], "presence", 0);
        return;
      }
    }
  }

  public void clearMonitor() {
    monitorList = new Vector<String>();
  }

  public void monitorSubscribe(SIPClient sip) {
    //subscribe for any that belong to sip
    String server = sip.getRemoteHost();
    for(int a=0;a<monitorList.size();a++) {
      String contact = monitorList.get(a);
      String fields[] = SIP.split(contact);
      if (fields[2].equalsIgnoreCase(server)) {
        sip.subscribe(fields[1], "presence", 3600);
      }
    }
  }

  public void onRegister(SIPClient sip) {
    if ((Settings.current.usePublish) && (presenceStatus.getSelectedIndex() == 0)) lines[line].sip.publish("open");
    monitorSubscribe(sip);
  }

  public Dimension getPreferredSize() {
    int x = 290;
    int y = 360;
    if (showingContacts || showingVideo) x += 270;
    if (showingVideo) y += 280;
    return new Dimension(x, y);
  }

  private VideoWindow videoWindow;

  private class LocalCamera extends Thread {
    private int cid, eid;
    private volatile boolean active = true;
    private volatile boolean done = true;
    public void run() {
      int res[] = Settings.current.getVideoResolution();
      cid = LnxAPI.gst_alloc_id();  //camera ID
      eid = LnxAPI.gst_alloc_id();  //encoder ID
      LnxAPI.gst_video_capture(cid, res[0], res[1], null);  //TODO : device ???
      if (!LnxAPI.gst_rtp_video_encoder(eid)) {
        JFLog.log("Error:Failed to init RTP Video Encoder");
        done = true;
        return;
      }
      localImage = new JFImage();
      localImage.setImageSize(320, 240);
      localCameraSender = new LocalCameraSender();
      localCameraSender.start();
      while (active) {
        JF.sleep(1000 / Settings.current.videoFPS);
        byte jpeg[] = LnxAPI.gst_video_capture_read(cid);
        if (jpeg == null) continue;
        JFImage tmp = new JFImage();
        tmp.loadJPG(new ByteArrayInputStream(jpeg));
        localImage.getGraphics().drawImage(tmp.getImage(), 0,0, 320,240, null);
        videoWindow.localVideo_setIcon(localImage);
        java.awt.EventQueue.invokeLater(new Runnable() {
          public void run() {
            videoWindow.repaint();
          }
        });
        LnxAPI.gst_rtp_video_encoder_write(eid, jpeg, res[0], res[1]);
      }
      LnxAPI.gst_stop(cid);
      LnxAPI.gst_free_id(cid);
      LnxAPI.gst_stop(eid);
      while (!localCameraSender.sender_done) {
        JFLog.log("Waiting for LocalCameraSender to stop");
        JF.sleep(5);
      }
      LnxAPI.gst_free_id(eid);
      done = true;
    }
    public void cancel() {
      active = false;
      while (!done) JF.sleep(5);
    }
    private class LocalCameraSender extends Thread {
      private boolean sender_done = false;
      public void run() {
        while (active) {
          byte data[] = LnxAPI.gst_rtp_video_encoder_read(eid);
          if (data == null) {JF.sleep(1000); JFLog.log("Warning:null from rtp_video_encode_read()"); continue;}
          rtp_jpeg_send(data, 0, data.length);
          JF.sleep(2);
        }
        sender_done = true;
      }
    }
    private LocalCameraSender localCameraSender;
    private JFImage localImage;
  }
  private LocalCamera localCamera;

  private class RemoteCamera extends Thread {
    private int did;
    private volatile boolean active = true;
    private volatile boolean done = true;
    public void run() {
      did = LnxAPI.gst_alloc_id();
      if (!LnxAPI.gst_rtp_video_decoder(did)) {
        JFLog.log("Error:Failed to init RTP Video Decoder");
        done = true;
        return;
      }
      remoteImage = new JFImage();
      remoteImage.setImageSize(320,240);
      while (active) {
        byte jpeg[] = LnxAPI.gst_rtp_video_decoder_read(did);
        if (jpeg == null) {JFLog.log("Warning:gst_rtp_decoder_read() returned null"); JF.sleep(1000); continue;}
        JFImage tmp = new JFImage();
        if (!tmp.load(new ByteArrayInputStream(jpeg))) {
          JFLog.log("RemoteCamera : failed to decode image");
          continue;
        }
        remoteImage.getGraphics().drawImage(tmp.getImage(), 0,0,320,240, null);
        videoWindow.remoteVideo_setIcon(remoteImage);
        java.awt.EventQueue.invokeLater(new Runnable() {
          public void run() {
            videoWindow.repaint();
          }
        });
      }
      LnxAPI.gst_stop(did);
      done = true;
    }
    public void rtp_data(byte data[], int pos, int len) {
      LnxAPI.gst_rtp_video_decoder_write(did, Arrays.copyOfRange(data, pos, pos+len));
    }
    public void cancel() {
      active = false;
      while (!done) JF.sleep(5);
    }
    private JFImage remoteImage;
  }
  private RemoteCamera remoteCamera;

  //Windows camera

  private class WLocalCamera extends Thread {
    private volatile boolean active = true;
    private volatile boolean done = true;
    public void run() {
      int res[] = Settings.current.getVideoResolution();
      if (Settings.current.videoWindowsAPI == Settings.VIDEO_WINDOWS_VFW) {
        int hwnd = WinAPI.get_window("JPLCamera");
        if (hwnd == 0) {
          JFLog.log("Error:Failed to get window handle of VideoWindow");
          return;
        }
        if (!WinAPI.vfw_open(hwnd, 5, 5, res[0], res[1], res[0], res[1])) {
          JFLog.log("Error:Failed to open Windows camera");
          done = true;
          return;
        }
        WinAPI.vfw_process();
      } else {
        if (!WinAPI.vi_open(0, res[0], res[1])) {
          JFLog.log("Error:Failed to open Windows camera");
          done = true;
          return;
        }
      }
      int xy[];
      if (Settings.current.videoWindowsAPI == Settings.VIDEO_WINDOWS_VFW) {
        xy = WinAPI.vfw_get_info();
      } else {
        xy = WinAPI.vi_get_info(0);
      }
      int cx = xy[0];
      int cy = xy[1];
      JFLog.log("camera size=" + cx + "x" + cy);
      wlocalImage = new JFImage();
      wlocalImage.setImageSize(320, 240);
      wlocalCameraSender = new WLocalCamera.WLocalCameraSender();
      wlocalCameraSender.start();
      while (active) {
        while (wList.size() > 0) {
          if (Settings.current.videoWindowsAPI == Settings.VIDEO_WINDOWS_VFW) WinAPI.vfw_process();
          JF.sleep(10);
        }
        JF.sleep(1000 / Settings.current.videoFPS);
        int px[];
        if (Settings.current.videoWindowsAPI == Settings.VIDEO_WINDOWS_VFW) {
          px = WinAPI.vfw_get_frame();
        } else {
          px = WinAPI.vi_get_frame(0);
        }
        if (px == null) continue;
//        JFLog.log("vfw:sending frame:length=" + px.length);
        JFImage tmp = new JFImage(cx, cy);
        tmp.putPixels(px, 0, 0, cx, cy, 0);
        wlocalImage.getGraphics().drawImage(tmp.getImage(), 0,0,320,240, null);
        if (Settings.current.videoWindowsAPI != Settings.VIDEO_WINDOWS_VFW) {
          //local camera is already visible in vfw
          videoWindow.localVideo_setIcon(wlocalImage);
          java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              videoWindow.repaint();
            }
          });
        }
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        tmp.saveJPG(baos);
//        JFLog.log("sending JPEG length=" + baos.toByteArray().length);
        byte packets[][] = rtpJpeg.encode(baos.toByteArray(), cx, cy);
        for(int a=0;a<packets.length;a++) {
          wList.add(packets[a]);
        }
        synchronized (wLock) {
          wLock.notify();
        }
      }
      if (Settings.current.videoWindowsAPI == Settings.VIDEO_WINDOWS_VFW) {
        WinAPI.vfw_close();
      } else {
        WinAPI.vi_close(0);
      }
      while (!wlocalCameraSender.sender_done) {
        JFLog.log("Waiting for WLocalCameraSender to stop");
        JF.sleep(5);
        synchronized (wLock) {
          wLock.notify();
        }
      }
      done = true;
    }
    public void cancel() {
      active = false;
      while (!done) {
        JF.sleep(5);
        synchronized (wLock) {
          wLock.notify();
        }
      }
    }
    private class WLocalCameraSender extends Thread {
      private boolean sender_done = false;
      public void run() {
        while (active) {
          if (wList.isEmpty()) {
            synchronized (wLock) {
              try { wLock.wait(); } catch (Exception e) {}
            }
          }
          byte data[] = wList.remove(0);
          if (data == null) continue;
          rtp_jpeg_send(data, 0, data.length);
          JF.sleep(2);
        }
        sender_done = true;
      }
    }
    private WLocalCamera.WLocalCameraSender wlocalCameraSender;
    private JFImage wlocalImage;
    private RTPJPEG rtpJpeg = new RTPJPEG();
    private final Object wLock = new Object();
    private Vector<byte[]> wList = new Vector<byte[]>();
  }
  private WLocalCamera wlocalCamera;

  private class WRemoteCamera extends Thread {
    private volatile boolean active = true;
    private volatile boolean done = true;
    public void run() {
      wremoteImage = new JFImage();
      wremoteImage.setImageSize(320,240);
      while (active) {
        synchronized (wLock) {
          try { wLock.wait(); } catch (Exception e) {}
        }
        if (wList.isEmpty()) continue;
        byte jpeg[] = wList.remove(0);
//        JFLog.log("received jpeg length=" + jpeg.length);
        JFImage tmp = new JFImage();
        if (!tmp.load(new ByteArrayInputStream(jpeg))) {
          JFLog.log("RemoteCamera : failed to decode image");
          continue;
        }
//        JFLog.log("jpeg size=" + tmp.getWidth() + "x" + tmp.getHeight());
        wremoteImage.getGraphics().drawImage(tmp.getImage(), 0,0,320,240, null);
        videoWindow.remoteVideo_setIcon(wremoteImage);
        java.awt.EventQueue.invokeLater(new Runnable() {
          public void run() {
            videoWindow.repaint();
          }
        });
      }
      done = true;
    }
    public void rtp_data(byte data[], int pos, int len) {
      byte jpeg[] = rtpJpeg.decode(Arrays.copyOfRange(data, pos, pos+len));
      if (jpeg != null) {
        wList.add(jpeg);
        synchronized (wLock) {
          wLock.notify();
        }
      }
    }
    public void cancel() {
      active = false;
      while (!done) {
        synchronized (wLock) {
          wLock.notify();
        }
        JF.sleep(5);
      }
    }
    private JFImage wremoteImage;
    private final Object wLock = new Object();
    private RTPJPEG rtpJpeg = new RTPJPEG();
    private Vector<byte[]> wList = new Vector<byte[]>();
  }
  private WRemoteCamera wremoteCamera;

  public void rtp_jpeg_receive(byte data[], int pos, int len) {
//    JFLog.log("rtp_jpeg_receive:len=" + len);
    if (Settings.isLinux) {
      if (remoteCamera == null) return;
      remoteCamera.rtp_data(data, pos, len);
      return;
    }
    if (Settings.isWindows) {
      if (wremoteCamera == null) return;
      wremoteCamera.rtp_data(data, pos, len);
      return;
    }
  }
  public String getLineStatus() {
    return status.getText();
  }

  public void toggleRecord() {
    if (line == -1) return;
    if (sound.record == null) {
      Record record = new Record();
      record.open();
      sound.record = record;
    } else {
      Record record = sound.record;
      sound.record = null;
      JF.sleep(40);
      record.close();
    }
    record.setIcon(ii[sound.record != null ? PIC_RED : PIC_GREY]);
  }
}
